[build]
  base = "client"
  command = "npm install && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NEXT_PUBLIC_API_URL = "https://nova-backend-htzd.onrender.com"

[[plugins]]
  package = "@netlify/plugin-nextjs"


